name: Autopublish to npm on release creation

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.target_commitish }}
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci

      - run: git config --global user.name "GitHub CD bot"
      - run: git config --global user.email "github-cd-bot@example.com"

      - run: git add . && git diff --staged --quiet || git commit -m "Update dependencies"

      - run: git status

      - run: npm version ${{ github.event.release.tag_name }} --no-git-tag-version

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Bump version to ${{ github.event.release.tag_name }}"
          file_pattern: "package.json package-lock.json"

      - uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
          tag: ${{ contains(github.event.release.tag_name, 'beta') && 'beta' || 'latest' }}

  show-npm-log:
    runs-on: ubuntu-latest
    needs: publish
    if: failure()
    steps:
      - run: echo "NPM Logs Directory:"
      - run: ls -l /home/runner/.npm/_logs/
      - run: echo "Displaying the most recent log:"
      - run: cat /home/runner/.npm/_logs/*.log